# Generated by Django 4.2 on 2024-06-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'permissions': [('can_comment_on_story', 'Can comment on story'), ('can_like_story', 'Can like story')]},
        ),
    ]
