# Generated by Django 4.2 on 2024-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, default='../two-ladies_iqfqjr', null=True, upload_to='images/'),
        ),
    ]
