# Generated by Django 4.2 on 2024-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='stories_images/'),
        ),
    ]
